---
- name: Automate Satellite Inventory Export to Git
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    # These variables are automatically populated from the
    # "Satellite API Credential" in Ansible Automation Platform/Tower
    satellite_url: "{{ satellite_api_credential_host }}"
    satellite_user: "{{ satellite_api_credential_username }}"
    satellite_api_key: "{{ satellite_api_credential_password }}" # Use password for API Key

  tasks:
    - name: Retrieve host data from Satellite API
      ansible.builtin.uri:
        url: "{{ satellite_url }}/api/v2/hosts"
        user: "{{ satellite_user }}"
        password: "{{ satellite_api_key }}"
        method: GET
        body_format: json
        validate_certs: false
        status_code: 200
        return_content: true
      register: satellite_data
      
    - name: Create formatted JSON inventory file
      ansible.builtin.copy:
        content: "{{ satellite_data.content | to_json(indent=2) }}"
        dest: "/path/to/your/git/repo/inventory.json"
      
    - name: Stage, commit, and push inventory file
      ansible.builtin.git:
        repo: 'https://github.com/your-org/your-repo.git'
        dest: '/path/to/your/git/repo'
        # The path should be relative to the repo root
        path: inventory.json
        state: present
        msg: "Automated Satellite inventory update: {{ ansible_date_time.iso8601_basic }}"
        push: true