---
- name: Automate Satellite Inventory Export to Git
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
    - name: Get url from environment
      ansible.builtin.set_fact:
        satellite_url: "{{ lookup('ansible.builtin.env', 'url') }}"
      no_log: true

    - name: Get username from environment
      ansible.builtin.set_fact:
        satellite_username: "{{ lookup('ansible.builtin.env', 'user') }}"
      no_log: true  

    - name: Get password from environment
      ansible.builtin.set_fact:
        satellite_password: "{{ lookup('ansible.builtin.env', 'password') }}"
      no_log: true

    - name: Retrieve host data from Satellite API
      ansible.builtin.uri:
        url: "{{ satellite_url }}"
        user: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        method: GET
        body_format: json
        validate_certs: false
        status_code: 200
        return_content: true
      register: satellite_data

    - name: Ensure github.com host key is in known_hosts
      ansible.builtin.known_hosts:
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        path: /home/{{ ansible_user }}/.ssh/known_hosts
        state: present

    - name: Ensure destination directory and repository exists
      ansible.builtin.git:
        repo: 'git@github.com:kersmaka/satellite.git'
        dest: '/home/ansible_admin/github/satellite/'
        version: 'main'
        update: true
        force: false
        recursive: true
        bare: false
        clone: true
        single_branch: false
        track_submodules: false

    - name: Create formatted JSON inventory file
      ansible.builtin.copy:
        content: "{{ satellite_data.content | to_json(indent=2) }}"
        dest: "/home/ansible_admin/github/satellite/inventory.json"
      
    - name: Stage, commit, and push inventory file
      ansible.builtin.shell:
        cmd: |
          cd /home/ansible_admin/github/satellite/
          git add inventory.json
          git commit -m "Automated Satellite inventory update: {{ ansible_date_time.iso8601_basic }}"
          git push