---
- name: Automate Satellite Inventory Export to Git
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Get url from environment
      ansible.builtin.set_fact:
        url: "{{ lookup('ansible.builtin.env', 'url') }}"
        
    - name: Retrieve host data from Satellite API
      ansible.builtin.uri:
        url: "{{ satellite_url }}"
        user: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        method: GET
        body_format: json
        validate_certs: false
        status_code: 200
        return_content: true
      register: satellite_data
      
    - name: Create formatted JSON inventory file
      ansible.builtin.copy:
        content: "{{ satellite_data.content | to_json(indent=2) }}"
        dest: "/path/to/your/git/repo/inventory.json"
      
    - name: Stage, commit, and push inventory file
      ansible.builtin.git:
        repo: 'https://github.com/your-org/your-repo.git'
        dest: '/path/to/your/git/repo'
        path: inventory.json
        state: present
        msg: "Automated Satellite inventory update: {{ ansible_date_time.iso8601_basic }}"
        push: true